version: '3.8'
services:
  eureka-server:
    image: eureka-server:0.0.1
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-net

networks:
  eureka-net:
    driver: bridge
